services:
  jenkins-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-mcp-server:latest
    container_name: jenkins-mcp-server
    restart: unless-stopped
    
    # Environment configuration
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_USERNAME=${JENKINS_USERNAME}
      - JENKINS_API_TOKEN=${JENKINS_API_TOKEN}
      - JENKINS_TIMEOUT=${JENKINS_TIMEOUT:-30000}
      - JENKINS_RETRIES=${JENKINS_RETRIES:-3}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - JENKINS_SSL_VERIFY=${JENKINS_SSL_VERIFY:-false}
      - JENKINS_SSL_ALLOW_SELF_SIGNED=${JENKINS_SSL_ALLOW_SELF_SIGNED:-true}
      - JENKINS_SSL_DEBUG=${JENKINS_SSL_DEBUG:-true}
    
    # Use stdin/stdout for MCP communication
    stdin_open: true
    tty: true
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.1'
    
    # Security context
    user: "1000:1000"
    read_only: true
    
    # Health check
    healthcheck:
      test: ["CMD", "sh", "-c", "echo '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\",\"params\":{}}' | jenkins-mcp-server"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Optional: Use external network for Jenkins connectivity
networks:
  default:
    name: jenkins-mcp-network
    driver: bridge
