name: Continuous Integration

# Simple CI workflow using Makefile commands - easy to replicate in any CI/CD system!
# For other CI systems, just use: make install && make quality

on:
  push:
    branches: [ main, develop, fix/docker-version-injection ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '2.4.5'

      - name: Install dependencies
        run: make install

      - name: Run comprehensive quality checks
        run: make quality-ci

      - name: Show project information
        run: make info

  # Cross-platform build test (simplified)
  build-test:
    name: Build Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '2.4.5'

      - name: Install and test
        run: |
          make install
          make quality-ci
        shell: bash

      - name: Test build for current platform
        run: make build-ci
        shell: bash
